### ISSUE TITLE
Investigate Config:Autoconf's "API harmonization / consolidation #5"

### ISSUE THREAD

**Issue by jeffreykegler** [jeffreykegler/Marpa--R2#178]
Investigate ambs/Config-AutoConf#5

**Comment by rehsack** [comment]
@jeffreykegler - any progress at this front? C::AC ships refactored half a year meanwhile ;)

**Comment by jeffreykegler** [comment]
I was expecting to hear from you, about how to tell if Marpa::R2 might be
affected: see
https://github.com/ambs/Config-AutoConf/issues/5#issuecomment-55948533

I am not sure whether you are telling the release will happen half a year
from now, or that it happened half a year ago.

**Comment by jeffreykegler** [comment]
I didn't see the notice that the this change would happen.  If I read the "Change" file correctly, the first indexed release with it was 0.307, which happened on 2014-12-14, which indeed is 6 months ago.

There have been no build problems over that period of time which could reasonably be traced back to Config::Autoconf.  I don't know if this answers your question or not.

**Comment by rehsack** [comment]
@jeffreykegler - I didn't see a request for a dedicated ping - I'm sorry that I didn't realize your wish.
However, https://github.com/ambs/Config-AutoConf/issues/5#issuecomment-65043942 should inform everyone at the thread about the progress. Hope you can go ahead now.

If you have any questions, please don't hesitate to ask me or @ambs

**Comment by jeffreykegler** [comment]
@ambs -- @rehsack and I got confused and so I'm not 100% clear on the state of this change.

Statement 1: I think the change under discussion went ahead and was part of 0.307 and every indexed CPAN release after that.  

Please confirm that Statement 1 in the above paragraph is correct.  If it is, I will close this issue.

If Statement 1 is correct, Marpa::R2 has actually been running with the proposed change for 5 months, because while Marpa::R2 requires a minimum version, it does not try to detect and prevent use of a more recent C::AC version.

This conversation got very confused, but "all is well that ends well".  Thanks!

**Comment by jeffreykegler** [comment]
As I said in the previous message, "all is well that end's well".  I think this discussion/issue came to a close back in May.
