### ISSUE TITLE
Minor doc patches for lexeme_alternative() and lexeme_read()

### ISSUE THREAD

**Issue by ronsavage** [jeffreykegler/Marpa--R2#224]
I refer to the (optional) value provided to lexeme_alternative() and lexeme_read(). I think the text means 'the value to be returned by Marpa'. I.e. you're saying force a lexeme to be read, but discard what's actually read and return the value provided by the caller. Is that the meaning?

**Comment by jeffreykegler** [comment]
Fixed in the commit just referenced.
