### ISSUE TITLE
Can't locate object method "rule_describe"

### ISSUE THREAD

**Issue by rns** [jeffreykegler/Marpa--R2#234]
test case: https://gist.github.com/rns/c0ac561941fec6848b87

To clarify -- `Marpa::R2::`*Grammar*`::rule_describe()` is called as as object method (which it isn't designed for) from `Marpa::R2::`*Value*`::rule_describe()`.

Note: in this case, `ambiguous()` and `ambiguity_metric()` do not differ, they (wrongly) think that the parse is ambiguous. The only difference with the [grammar for which they do differ](https://gist.github.com/rns/d9c45866a3219ce93d7b) is that this grammar has actions, e.g. `action => _unicodeDelimitedIdentifier`.

**Comment by jeffreykegler** [comment]
Fixed in commit 77dfdb3bac174b12f07b9c9039a4e0818a855d0a I think.  The test case gets past the problem to another error, which looks like it is in the application.  Want to test?

**Comment by rns** [comment]
Sure. ;) it doesn't find actions in ASF constructor; with actions removed from the grammar, it produces this:
```
ambiguity_metric: 2
ambiguous status: ''
```
so the behaviour is the same as in #233, `rule_describe()` bug is fixed and this issue can be closed.
