### ISSUE TITLE
Doc fix for Scanless/R.pod

### ISSUE THREAD

**Issue by ronsavage** [jeffreykegler/Marpa--R2#244]
Marpa::R2::Scanless::R.pod lines 268 .. 273.

Probably what is meant - by the first sentence - is "... a new virtual input string, being a substring of the stringref passed to C<read()>, starting at the current position, or at a new position as specified in the call to C<resume>".

The C<resume()> method uses a new input string to scan
the physical input stream that was specified
to the C<read()> method.
C<resume()>'s input string may be specified explicitly or implicitly.
By default, the new input string runs from the current location
to the end of the physical input stream.

Change to something like:

The C<resume()> method resumes the scan of 
the physical input stream that was specified
to the C<read()> method as a stringref.
C<resume()>'s starting position may be specified explicitly or implicitly.
By default, the new scan runs from the current location - as returned
by C<read()> -, and continues
to the end of the physical input stream.

**Comment by jeffreykegler** [comment]
I took a stab at it.  If I don't hear anything, I'll close this shortly.

**Comment by ronsavage** [comment]
Hi Jeffrey

I'm sure someone somewhere will misunderstand, but let's leave it at that.

On 19/02/15 14:58, Jeffrey Kegler wrote:
> I took a stab at it. If I don't hear anything, I'll close this shortly.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jeffreykegler/Marpa--R2/issues/244#issuecomment-74995889>.
>

-- 
Ron Savage - savage.net.au
