### ISSUE TITLE
Doc issue for Marpa/R2/Scanless/DSL

### ISSUE THREAD

**Issue by ronsavage** [jeffreykegler/Marpa--R2#250]
Under Discard pseudo-rule (at the end) it says:
Only the event adverb is allowed. Its value must be an event initializer. The format of an event initializer is described above.
But under Event initializer all examples are of the form:
x = completed y
This makes it look like 'completed y' is mandatory.
But the 2nd example under Discard pseudo-rule says:
:discard ~ whitespace event => ws

**Comment by jeffreykegler** [comment]
I addressed this in the two commits just referenced.  Let me know what you think!

**Comment by ronsavage** [comment]
Hi Jeffrey

Yes, that should do.

On 09/03/15 10:13, Jeffrey Kegler wrote:
> I addressed this in the two commits just referenced. Let me know what
> you think!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jeffreykegler/Marpa--R2/issues/250#issuecomment-77781188>.
>

-- 
Ron Savage - savage.net.au
