### ISSUE TITLE
SLIF does not respect blessed per-parse arguments

### ISSUE THREAD

**Issue by latk** [jeffreykegler/Marpa--R2#254]
I am not sure whether this is a bug, a documentation bug, or per-design, but it's surely annoying. This issue is a more thorough discussion of the problem mentioned in http://irclog.perlgeek.de/marpa/2015-05-02#i_10537778 and http://irclog.perlgeek.de/marpa/2015-05-03#i_10538150

# The problem

The documentation for [Marpa::R2::Scanless::R::value](https://metacpan.org/pod/Marpa::R2::Scanless::R#value) indicates that the argument to value `$recce->value($arg)` will be the per-parse value for all rule evaluation closures.

The Semantics documentation instead states that if a per-parse constructor exists (i.e. a `new` sub in the semantics package), then [the argument of `$recce->value` will be used as the sole argument to the per-parse constructor](https://metacpan.org/pod/Marpa::R2::Semantics#The-per-parse-argument). This makes sense if both the value argument is not blessed, and also the per-parse constructor is a function instead of a method. But if the value argument is blessed, this leads to highly unintuitive behaviour.

Consider this program, using Moo for OOP support. It accidentally works, obscuring the problem:

``` perl
package MyActions;
use Moo;
use feature 'say';
use Marpa::R2;
 
sub parse {
    my ($class, $input) = @_;
    my $grammar = Marpa::R2::Scanless::G->new({ source => \q(A ::= 'a' action => do_A) });
    my $recce = Marpa::R2::Scanless::R->new({ grammar => $grammar });
    $recce->read(\$input);
    my $per_parse_argument = $class->new;
    my $value = $recce->value($per_parse_argument);
    return $$value;
}
 
sub do_A {
    my ($self, $letter) = @_;
    return "read '$letter'";
}
 
say MyActions->parse('a');
```

This resolves `MyActions` as the semantics package, and sets the per-parse argument to a `MyActions` instance – but not to the same instance we passed to the `$recce->value` method!

However, the `new` method might not be a “default constructor”, in which case the difference can be seen:

``` perl
package MyActions;
use Moo;
use feature 'say';
use Marpa::R2;
 
has data => (
    is => 'ro',
    required => 1,
);
 
sub parse {
    my ($class, $input) = @_;
    my $grammar = Marpa::R2::Scanless::G->new({ source => \q(A ::= 'a' action => do_A) });
    my $recce = Marpa::R2::Scanless::R->new({ grammar => $grammar });
    $recce->read(\$input);
    my $per_parse_argument = $class->new(data => "foo");
    my $value = $recce->value($per_parse_argument);
    return $$value;
}
 
sub do_A {
    my ($self, $letter) = @_;
    return "read '$letter'";
}
 
say MyActions->parse('a');

```

This will now blow up with a cryptic error message:

``` plain
============================================================
* THE MARPA SEMANTICS PRODUCED A FATAL ERROR
* THIS IS WHAT MARPA WAS DOING WHEN THE PROBLEM OCCURRED:
constructing action object
* THIS WAS THE FATAL ERROR MESSAGE:
Missing required arguments: data at (eval 136) line 49.
Marpa::R2 exception at so2.pl line 18.
```

The problem is that Marpa does something like this:

``` perl
$semantics_package //= ref $argument_to_value // die;
if (my $code = *{ $semantics_package . '::new' }{CODE}) {
    $per_parse_constructor = $code ;
}
my $per_parse_argument = $argument_to_value;
if ($per_parse_constructor) {
    my $ctor_argument = $per_parse_argument // $semantics_package;
    eval { $per_parse_argument = $per_parse_constructor->($ctor_argument) };
}
...
```

(for the real code, see https://github.com/jeffreykegler/Marpa--R2/blob/491cb3b0cea473ae79978037c24455b3d73c8b4a/cpan/lib/Marpa/R2/Value.pm#L1356-L1560)

This means that if the `$argument_to_value` is a blessed object, the actual parse argument will be set to `$argument_to_value->new`! While some people implement `$instance->new` as a clone operation, this requirement is not obvious, and in fact makes it impossible to use a `new` method as commonly used in Perl:

``` perl
sub new {
    my ($class, %args) = @_;
    validate(\%args);
    return bless \%args, $class;
}
```

If we want to pass arguments to a per-parse constructor with Marpa, we need to create an otherwise unusable `new` function:

``` perl
sub new {
    my ($args) = @_;
    # the first arg might be a reference or the name of the semantics package
    # in that case, substitute an empty hashref
    $args = {} if not ref $args;
    validate($args);
    return bless $args, __PACKAGE__;
}
```

Oh dear. Note that object systems such as Moo do not really support such weird constructors.

# Suggested Solution

If the argument to `$recce->value` is a blessed object, do not apply the per-parse constructor to it. Instead, use that object directly and only validate that `$object->DOES($semantics_package)`, or if you really want to rule out inheritance that `ref($object) eq $semantics_package`.

# Temporary Workarounds

  - hide the `new` sub from Marpa when calling `$recce->value`. Note that this solution is not reentrant.

    ``` perl
    ...
    my $per_parse_argument = MyActions->new(%args);
    local *MyActions::new;
    my $value = $recce->value($per_parse_argument);
    ```

  - don't use helpful modules like `Moo`, and instead write constructors and accessors manually – or don't use objects at all. Apparently, Marpa isn't really meant to be used in an OOP context.

  - use a different package for the semantics and the per-parse object. For example, we could use a `Moo::Role`  for the semantics package, and have a `Moo` class inherit from that which is used to create the object. Since roles do not have a `new` method, there's no per-parse constructor to interfere. However, I'm surprised this actually works since the per-parse argument isn't directly blessed into the `MyActions` semantics package.

    ``` perl
    package MyActions;
    use Moo::Role;
    use feature 'say';
    use Marpa::R2;
     
    has data => (
        is => 'ro',
        required => 1,
    );
    
    {
        package MyActions::Impl;
        use Moo;
        with 'MyActions';
    }
 
    sub parse {
        my ($class, $input) = @_;
        my $grammar = Marpa::R2::Scanless::G->new({ source => \q(A ::= 'a' action => do_A) });
        my $recce = Marpa::R2::Scanless::R->new({ grammar => $grammar, semantics_package => 'MyActions' });
        $recce->read(\$input);
        my $per_parse_argument = $class->new(data => "foo");
        my $value = $recce->value($per_parse_argument);
        return $$value;
    }
     
    sub do_A {
        my ($self, $letter) = @_;
        return "read '$letter'";
    }
     
    say MyActions::Impl->parse('a');
```

**Comment by jeffreykegler** [comment]
My current theory is that this is a Marpa::R2 code bug.

The argument to $recce_value(), if it exists, should become the per-parse object, unaltered.  I read the docs as saying this is what happens.

If there is an explicitly specified `semantics_packaage` and an arg to `value()`, no per-parse constructor should be invoked, and the semantics should come from `semantics_package`, regardless of any blessing of the arg to `value()`.  I think this is what the docs state.

**Comment by jeffreykegler** [comment]
@latk -- if you could create a test case, it would help me get started.  Whenever I can, I try to do test-based development working from it.  You have most of it above, but the extra 10% often requires an unexpectly time-consuming and error-prone guessing on my part.  Moo-free, plese.

**Comment by rns** [comment]
My take at the test case -- https://gist.github.com/rns/d32bfd22893b7c80c50c, hope it reproduces the problem. @latk?

**Comment by jeffreykegler** [comment]
Uploaded the fix to CPAN as Marpa-R2-2.105_000

**Comment by latk** [comment]
Thanks @jeffreykegler and @rns for your help with this. I just installed the new release, and verified that it works fine with both my example code and my actual project :)

The [diff](https://github.com/jeffreykegler/Marpa--R2/compare/5886a40...547cf0b) looks fairly nice. While this change technically is backwards-incompatible, it is unlikely that this will break much code. 

Re-reading the [corresponding FAQ in the Marpa Papers](http://savage.net.au/Perl-modules/html/marpa.papers/chapter3.html#q23), it seems almost insane what other people have done to work around the weird previous behaviour. Ron writes: “*\[Using an action object\] seems like it works accidently, and I feel deeply uneasy about that. And, worse, it could suddenly stop working when any of Perl, Moo or Marpa change internally.*” Now, there's a way to use action objects that work non-accidentally. I plan to write a pull request for the Marpa Papers when I have some free time later this week.

**Comment by jeffreykegler** [comment]
Thanks.  Next step is to post an announcement of the proposed Marpa 3.0 to the Google group, asking for comments.
