### ISSUE TITLE
require on perl version >= 5.10.0 is missing

### ISSUE THREAD

**Issue by rns** [jeffreykegler/Marpa--R2#257]
reported by @jdurand on IRC -- http://irclog.perlgeek.de/marpa/2015-05-07#i_10560698

**Comment by jeffreykegler** [comment]
"... from http://fast-matrix.cpantesters.​org/?dist=Marpa-R2%202.105_000 I suspect a require on perl version >= 5.10.0 is missing"

**Comment by jeffreykegler** [comment]
Fixed in above referenced commit.
