### ISSUE TITLE
wishlist: externalize $problem_code

### ISSUE THREAD

**Issue by jddurand** [jeffreykegler/Marpa--R2#260]
In case an exception is raised, it might be great if the caller can recuperate `$problem_code` that is raised by `$thin_slr->read()` instead of having only the string generated by the exception.

**Comment by jeffreykegler** [comment]
Added to the wishlist

**Comment by jeffreykegler** [comment]
@jddurand Do you want to refile this as a Marpa::R3 issue?  That way you can rephrase, etc., based on any thinking you've done on this.  If not, I'll copy it and close it.

**Comment by jddurand** [comment]
Well, you can copy/paste/close!
Thx - Cheers

**Comment by jeffreykegler** [comment]
Copied to above referenced Marpa--R3 issue.
