### ISSUE TITLE
Reword error msg

### ISSUE THREAD

**Issue by ronsavage** [jeffreykegler/Marpa--R2#262]
'A lexeme in G1 is not a lexeme in any of the lexers: digit'
could become
'An L0 lexeme cannot appear on the RHS of an L0 rule'

**Comment by jeffreykegler** [comment]
Thanks!  I'm keeping Marpa::R2 stable, but when a bug comes along to justify release, I'll include this change.

**Comment by jeffreykegler** [comment]
Closed with above referenced commit.  Thanks!
