### ISSUE TITLE
Symbols can't contain accented characters

### ISSUE THREAD

**Issue by choroba** [jeffreykegler/Marpa--R2#268]
Running the following code prints `1`, which means all the characters match `\w`, but it then dies with

```
Parse of BNF/Scanless source failed
Error in SLIF parse: No lexeme found at line 5, column 9
* String before error:  []\nlexeme default = latm => 1\n\n<\x{0160}> ::=\s
* The error was at line 5, column 9, and at character 0x003c '<', ...
* here: <\xc1> <\x{010c}>\n<\xc1> ::= a+\n<\x{010c}> ::= c
Marpa::R2 exception at /home/choroba/1.pl line 24.
Marpa::R2 exception at /home/choroba/1.pl line 24.
```

Removing `<>` doesn't help.

I'm not sure whether Marpa should/could be improved to handle such symbols, or just its documentation should mention it doesn't.

```
#!/usr/bin/perl
use warnings;
use strict;
use utf8;

use Marpa::R2;

print "ŠÁČ" =~ /^\w+$/, "\n";

my $dsl = << '__DSL__';

:default ::= action => []
lexeme default = latm => 1

<Š> ::= <Á> <Č>
<Á> ::= a+
<Č> ::= c

a ~ 'a'
c ~ 'c'

__DSL__

my $grammar = 'Marpa::R2::Scanless::G'->new({ source => \$dsl });
```

Also discussed at [IRC](http://irclog.perlgeek.de/marpa/2016-03-19#i_12209115).

**Comment by jeffreykegler** [comment]
Thanks for filing this!

**Comment by jeffreykegler** [comment]
I am able to duplicate the problem on my development box.  Some accented characters do seem to work.  In this example, the <Š> works OK, but <Á> and  <Č> have problems.

**Comment by choroba** [comment]
Confirmed. I also veryfied it's not related to the fact that Š doesn't appear on the RSH of any rule.

**Comment by jeffreykegler** [comment]
Thanks!  Fixed in Marpa::R3.  Will never be fixed in Marpa::R2.

**Comment by jeffreykegler** [comment]
Fixed with commit 5b14fd31ad868a5137ab6374893831ade791e6e4.  This will appear in a soon forthcoming release.

**Comment by jeffreykegler** [comment]
Fixed in the next release, which I hope will be within a week or two.

**Comment by choroba** [comment]
👍 Great, thanks!

**Comment by jeffreykegler** [comment]
I also talked about this on the IRC channel just now: https://irclog.perlgeek.de/marpa/2017-02-26#i_14168611

**Comment by jeffreykegler** [comment]
@choroba Btw, if when the developer's release(s) come out you could test this, I'd greatly appreciate it.  There's a test in the test suite, but it's a single very simple instance.  Marpa::R2 releases are rare, so it's useful to make sure a fix is indeed a fix before the release is finalized.

**Comment by jeffreykegler** [comment]
Were you able to look at this fix?  It tests 100% OK on CPANtesters but, if possible, I'd like to confirm that it actually fixes your issue before making the full indexed release.

**Comment by choroba** [comment]
Not yet, thanks for reminding me. I'll do it ASAP.

**Comment by choroba** [comment]
☑️ Confirmed

**Comment by jeffreykegler** [comment]
Thanks!
