### ISSUE TITLE
ASF all_choices

### ISSUE THREAD

**Issue by jddurand** [jeffreykegler/Marpa--R2#271]
The current implementation assumes that a child value is an array reference:

```
        my $child_value = $values[$rh_ix];
        for my $new_value ( @{ $child_value } ) {
            push @new_results, [ @{$old_result}, $new_value ];
        }
```

Nevertheless this is not always the case, and a crash is easily reproducible by add a call to

```
$glade->all_choices();
```

in the pruning traverser given in the POD, when the current symbol is a rule id.

**Comment by jddurand** [comment]
For instance, if the end of the pruning traverser is:

    $glade->all_choices();
    my $length = $glade->rh_length();
    my @return_value = map { $glade->rh_value($_) } 0 .. $length - 1;

    # Special case for the start rule
    return (join q{ }, @return_value) . "\n" if  $symbol_name eq '[:start]' ;

    my $join_ws = q{ };
    $join_ws = qq{\n   } if $symbol_name eq 'S';
    my $penn_tag = penn_tag($symbol_name);
    return "($penn_tag " . ( join $join_ws, @return_value ) . ')';

then:

 ```
 Uncaught exception from user code:
	Can't use string ("(DT a)") as an ARRAY ref while "strict refs" in use at /home/jdurand/perl5/perlbrew/perls/perl-5.23.7-debug/lib/site_perl/5.23.7/i686-linux/Marpa/R2/ASF.pm line 1372, <DATA> line 1.
	Marpa::R2::Internal::ASF::Traverse::all_choices(Marpa::R2::Internal::ASF::Traverse=ARRAY(0x9c6b6a8)) called at test/marpaWrapperAsfTester.pl line 56
	main::pruning_traverser(Marpa::R2::Internal::ASF::Traverse=ARRAY(0x9c6b6a8), HASH(0x9c36550)) called at /home/jdurand/perl5/perlbrew/perls/perl-5.23.7-debug/lib/site_perl/5.23.7
```

**Comment by jddurand** [comment]
I now think that rh_values() should return an array of [ rh_value ] instead of an array of rh_value -;

**Comment by jeffreykegler** [comment]
Note to myself: The complaint sees to be about `$glade->all_choices()` -- that's the title of the issue, and that's where the code snippet is from.

**Comment by jeffreykegler** [comment]
@jddurand What do you think of commit de2fc744bec9e143899edbc7e6f0b51e8346aa73 -- also referenced above -- as the fix?

**Comment by jeffreykegler** [comment]
The above referenced commit is this same fix carried forward to Marpa::R2

**Comment by jddurand** [comment]
Looks fine - tested here locally and it is ok -  many thanks.

**Comment by jeffreykegler** [comment]
Closed as fixed, as per the last 2 posts.
