### ISSUE TITLE
Expressing a prioritized rule more than once

### ISSUE THREAD

**Issue by jddurand** [jeffreykegler/Marpa--R2#273]
It raises the exception shown below - I do not know if this is documented that it is not allowed (?). Anyway, this is because ``Marpa::R2::Internal::MetaAST_Nodes::priority_rule::evaluate`` takes the unary starting at zero at every evaluation  - a simple fix could be to have an internal number at the package level instead.

```
use Marpa::R2;

my $grammar = Marpa::R2::Scanless::G->new(
                                          {   bless_package => 'My_Nodes',
                                              source        => \(<<'END_OF_SOURCE'),
    comma ~ [,]
    <Expression> ::=
        Number bless => primary rank => 10
        | '(' Expression ')' bless => paren assoc => group
       || Expression '**' Expression bless => exponentiate assoc => right
       || Expression '*' Expression bless => multiply
        | Expression '/' Expression bless => divide rank => 10
       || Expression '+' Expression bless => add
        | Expression '-' Expression bless => subtract

    <Expression> ::=
        Number 'x' bless => primary rank => 10
        | '(' Expression 'y' ')' bless => paren assoc => group
       || Expression '**' Expression 'z' bless => exponentiate assoc => right

    Number ~ [\d]+
END_OF_SOURCE
```
The exception is:
``
Duplicate rule: Expression -> Expression[0]
``

**Comment by jeffreykegler** [comment]
It should not be allowed, and if the docs do not say so, it's a documention bug.

The problem is that it's not clear how alternatives in the 2nd prioritized statement should be ranked relative to those in the first.  The priorities must be a full order, not a partial one.

**Comment by jeffreykegler** [comment]
What happened with this?  Back in Nov, I thought the behavior was OK, and wondered if the docs were misleading.  We may have an R2 release soon, in which case the docs could be clarified.

**Comment by jddurand** [comment]
IMHO a mention in the doc is fair enough

**Comment by jeffreykegler** [comment]
Doc fix made in the above referenced commit.

**Comment by jeffreykegler** [comment]
Also fixed in Marpa::R3, but forgot to refer back to Marpa::R2 when I put the issue number in the commit.
