### ISSUE TITLE
Confusion about length of libmarpa token

### ISSUE THREAD

**Issue by jeffreykegler** [jeffreykegler/Marpa--R2#280]
Some confusion about the length of a libmarpa token may have propagated upward.  The libmarpa macros involved are `marpa_v_es_id()` and `marpa_v_token_start_es_id()`.  Affected might be the `g1length` descriptor and `MARPA_OP_PUSH_G1_LENGTH` in R2.xs.  In particular, line https://github.com/jeffreykegler/Marpa--R2/blob/2ef61bdf4d0ff2de3503ca136dbe4a18ff742f9b/cpan/xs/R2.xs#L1806 seems to be wrong.

The solution at this point is probably not to fix R2.xs, which will break everybody depending on the misfeature, but to document that, "for historical reasons", `g1length` is not what you would expect.

**Comment by jddurand** [comment]
Jeffrey,

Can you explain the confusion in itself and would be the fix if you were to change to code ?

Thanks, JD.

**Comment by jeffreykegler** [comment]
Also in error is this line:

https://github.com/jeffreykegler/Marpa--R2/blob/2ef61bdf4d0ff2de3503ca136dbe4a18ff742f9b/cpan/xs/R2.xs#L1798

**Comment by jeffreykegler** [comment]
@jddurand If I were to change the code, everyone using the `g1length` [action array descriptor](https://metacpan.org/dist/Marpa-R2/view/pod/Semantics.pod#Array-descriptor-actions) for tokens and rules (but not nulling symbols) would see a value that is lesser by one.  This would make more sense but would break everything relying on the current behavior.

**Comment by jeffreykegler** [comment]
Per https://github.com/jeffreykegler/Marpa--R2/issues/280#issuecomment-1347133777, I am closing this issue.
