### ISSUE TITLE
CI: Does Travis-CI still work for you?

### ISSUE THREAD

**Issue by szabgab** [jeffreykegler/Marpa--R2#289]
If not, would you be interested in a PR to set up GitHub Actions for CI?

**Comment by jeffreykegler** [comment]
Many thanks for the generous offer.

I used Travis a lot, but it went behind a paywall, so I could not use it any more.

**Comment by jddurand** [comment]
@jeffreykegler , @szabgab is proposing a PR for github actions, not travis, that are free of charge, and powerful.

**Comment by szabgab** [comment]
OK. I'll try to do it and post about it in my [Daily CI](https://dev.to/szabgab/the-2022-december-ci-challenge-5dof) series.

**Comment by jeffreykegler** [comment]
I feel ungrateful to ask for more in the face of this generosity, but if someone would take on to fork a downstream testing repo, this would take a burden off me.  Currently I am 50% doing admin stuff, and the other 50% is divided among new development, papers, documentation

**Comment by szabgab** [comment]
> if someone would take on to fork a downstream testing repo, 

I don't think I'd be able to do that, but which repo are you talking about?

**Comment by jeffreykegler** [comment]
Actually, let me think out how I'd want to do the testing/packaging repo.

@szabgab But thanks for the Daily CI piece, which I will very much look look forward to!

**Comment by jeffreykegler** [comment]
@szabgab -- thanks for the pull request!  Absent feedback to the contrary, I will close this issue after a couple of days.

**Comment by szabgab** [comment]
[Here](https://dev.to/szabgab/day-16-moving-from-travis-ci-to-github-actions-for-marpar2-21cj) is the post about the PR #292

**Comment by jeffreykegler** [comment]
I commented on [Gabor's dev.to post](https://dev.to/szabgab/day-16-moving-from-travis-ci-to-github-actions-for-marpar2-21cj).  I expect that this moves the discussion onto dev.to.  Absent further feedback on this issue, I will close it after a couple of days.

**Comment by jeffreykegler** [comment]
Closed per https://github.com/jeffreykegler/Marpa--R2/issues/289#issuecomment-1356867815.
