### ISSUE TITLE
Use of uninitialized value in numeric eq (==) at /usr/lib/x86_64-linux-gnu/perl-base/IO/Select.pm line 68.

### ISSUE THREAD

**Issue by szabgab** [jeffreykegler/Marpa--R2#290]
I got this warning several times while running `./Build`. I know is not in Marpa::R2 but maybe it is caused by it.

**Comment by jeffreykegler** [comment]
I take it this is during install?  Could you send me a log?  I don't see this on my setup.

**Comment by szabgab** [comment]
I had version 1.46 of IO::Select on perl 5.34.0

Using IO::Select version 1.49 that I got after upgrading it (it was in the  IO-1.50 package) I don't have the warning any more.
I reported the package version number issue:  Perl/perl5/#20609

**Comment by jeffreykegler** [comment]
Whew!

May I schedule this for closing on the basis that it is unlikely to be a Marpa::R2 issue?

**Comment by szabgab** [comment]
Sure.

**Comment by jeffreykegler** [comment]
Per https://github.com/jeffreykegler/Marpa--R2/issues/290#issuecomment-1352575820, and absent feedback to the contrary, I will close this issue after a couple of days.

**Comment by jeffreykegler** [comment]
Closed per https://github.com/jeffreykegler/Marpa--R2/issues/290#issuecomment-1352584869.
