### ISSUE TITLE
cpan/engine/read_only/tests/* files missing

### ISSUE THREAD

**Issue by szabgab** [jeffreykegler/Marpa--R2#291]
In the `perl Build.PL` step it is just a warning, but in the `./Build disttest` step fails because of this.
Should these files be generated or should they be removed from the `cpan/MANIFEST` file?

```
$ perl Build.PL 
WARNING: the following files are missing in your kit:
	engine/read_only/tests/libtap.sh
	engine/read_only/tests/runtests.c
	engine/read_only/tests/simple/depr_unvalued.c
	engine/read_only/tests/simple/issue92a.c
	engine/read_only/tests/simple/issue92b.c
	engine/read_only/tests/simple/issue92c.c
	engine/read_only/tests/simple/marpa_m_test.c
	engine/read_only/tests/simple/marpa_m_test.h
	engine/read_only/tests/simple/nits.c
	engine/read_only/tests/simple/rule1.c
	engine/read_only/tests/simple/trivial.c
	engine/read_only/tests/simple/trivial1.c
	engine/read_only/tests/tap/basic.c
	engine/read_only/tests/tap/basic.h
	engine/read_only/tests/tap/float.c
	engine/read_only/tests/tap/float.h
	engine/read_only/tests/tap/macros.h
	engine/read_only/tests/TESTS
	META.json
	META.yml
Please inform the author.

Created MYMETA.yml and MYMETA.json
Creating new 'Build' script for 'Marpa-R2' version '11.004_000'
```

this later causes problem:

```
$ ./Build disttest
Created META.yml and META.json
Revised META.yml and META.json
Creating Marpa-R2-11.004_000
Can't copy('engine/read_only/tests/TESTS', 'Marpa-R2-11.004_000/engine/read_only/tests/TESTS'): No such file or directory at /usr/share/perl5/Module/Build/Base.pm line 5606
```

**Comment by jeffreykegler** [comment]
That looks like the version hot off the repo.  disttest works on my box (Rasperry Pi OS).

Did you build from scratch?  This looks very much like what would happen if you're mixing versions.

**Comment by jeffreykegler** [comment]
I think I found the problem, which should be fixed in commit https://github.com/jeffreykegler/Marpa--R2/commit/529792ba74567020d5580f888057a8df9d6c8ffd.  Those files had not been added to to git.

**Comment by szabgab** [comment]
I can confirm, it works now.

**Comment by jeffreykegler** [comment]
FYI many programmers make a point of the tip of their main branch being something useable.  I am NOT one of them, so pulling from my repo, instead of a distribution, is risky.

**Comment by jeffreykegler** [comment]
Per https://github.com/jeffreykegler/Marpa--R2/issues/291#issuecomment-1352668369, this is fixed.  Absent feedback to the contrary, I will close this issue after a couple of days.

**Comment by szabgab** [comment]
I would say it is a good practice to ensure all the test are always passing on the tip of the main branch. Otherwise one would risk starting to think that "some tests always fail" which could lead to some test failing that *should not fail* go unnoticed for a long period of time.

Also it upsets the CI and we don't want to do that :)

But if all the tests are passing, doesn't that mean that the version is usable?

**Comment by jeffreykegler** [comment]
I answered https://github.com/jeffreykegler/Marpa--R2/issues/291#issuecomment-1354246135 in [this comment on dev.to](https://dev.to/jeffreykegler/comment/23g7k).  Absent feedback to the contrary, I will close this issue after a couple of days.

**Comment by jeffreykegler** [comment]
Closed per https://github.com/jeffreykegler/Marpa--R2/issues/291#issuecomment-1356865899.
