### ISSUE TITLE
RT CPAN issue 14563

### ISSUE THREAD

**Issue by jeffreykegler** [jeffreykegler/Marpa--R2#293]
This is for rt.cpan issue https://rt.cpan.org/Public/Bug/Display.html?id=145623.

**Comment by jeffreykegler** [comment]
I DuckDuckGo'd the error, and it appears to be due to a problem in GNU configure.

If fixing GNU configure is not convenient or possible, adding the following to your environment may be a workaround:

``` MARPA_USE_PERL_AUTOCONF=1 ```

This environment setting will cause the installation to use Perl's Config::Autoconf instead of the GNU autoconf.

I hope this helps!

**Comment by rameshrella** [comment]
Hi Jeffrey

Thanks a lot...!

It works for me.

**Comment by jeffreykegler** [comment]
I am glad it worked.  Absent feedback to the contrary, I will close this issue after a couple of days.

**Comment by jeffreykegler** [comment]
Closed per https://github.com/jeffreykegler/Marpa--R2/issues/293#issuecomment-1361488009.
